/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as SubscriptionsRouteImport } from './routes/subscriptions'
import { Route as StoreLocatorRouteImport } from './routes/store-locator'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SearchRouteImport } from './routes/search'
import { Route as MissionRouteImport } from './routes/mission'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ThoughtsIndexRouteImport } from './routes/thoughts.index'
import { Route as JournalsIndexRouteImport } from './routes/journals.index'
import { Route as EbooksIndexRouteImport } from './routes/ebooks.index'
import { Route as CategoriesIndexRouteImport } from './routes/categories.index'
import { Route as BooksIndexRouteImport } from './routes/books.index'
import { Route as AuthorsIndexRouteImport } from './routes/authors.index'
import { Route as AccountIndexRouteImport } from './routes/account.index'
import { Route as ThoughtsSlugRouteImport } from './routes/thoughts.$slug'
import { Route as JournalsSlugRouteImport } from './routes/journals.$slug'
import { Route as EbooksSlugRouteImport } from './routes/ebooks.$slug'
import { Route as CategoriesSlugRouteImport } from './routes/categories.$slug'
import { Route as BooksSlugRouteImport } from './routes/books.$slug'
import { Route as AuthorsSlugRouteImport } from './routes/authors.$slug'
import { Route as AccountOrdersRouteImport } from './routes/account.orders'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionsRoute = SubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreLocatorRoute = StoreLocatorRouteImport.update({
  id: '/store-locator',
  path: '/store-locator',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionRoute = MissionRouteImport.update({
  id: '/mission',
  path: '/mission',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThoughtsIndexRoute = ThoughtsIndexRouteImport.update({
  id: '/thoughts/',
  path: '/thoughts/',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalsIndexRoute = JournalsIndexRouteImport.update({
  id: '/journals/',
  path: '/journals/',
  getParentRoute: () => rootRouteImport,
} as any)
const EbooksIndexRoute = EbooksIndexRouteImport.update({
  id: '/ebooks/',
  path: '/ebooks/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesIndexRoute = CategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksIndexRoute = BooksIndexRouteImport.update({
  id: '/books/',
  path: '/books/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorsIndexRoute = AuthorsIndexRouteImport.update({
  id: '/authors/',
  path: '/authors/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThoughtsSlugRoute = ThoughtsSlugRouteImport.update({
  id: '/thoughts/$slug',
  path: '/thoughts/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalsSlugRoute = JournalsSlugRouteImport.update({
  id: '/journals/$slug',
  path: '/journals/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EbooksSlugRoute = EbooksSlugRouteImport.update({
  id: '/ebooks/$slug',
  path: '/ebooks/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesSlugRoute = CategoriesSlugRouteImport.update({
  id: '/categories/$slug',
  path: '/categories/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksSlugRoute = BooksSlugRouteImport.update({
  id: '/books/$slug',
  path: '/books/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorsSlugRoute = AuthorsSlugRouteImport.update({
  id: '/authors/$slug',
  path: '/authors/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountOrdersRoute = AccountOrdersRouteImport.update({
  id: '/account/orders',
  path: '/account/orders',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/mission': typeof MissionRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/store-locator': typeof StoreLocatorRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/wishlist': typeof WishlistRoute
  '/account/orders': typeof AccountOrdersRoute
  '/authors/$slug': typeof AuthorsSlugRoute
  '/books/$slug': typeof BooksSlugRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/ebooks/$slug': typeof EbooksSlugRoute
  '/journals/$slug': typeof JournalsSlugRoute
  '/thoughts/$slug': typeof ThoughtsSlugRoute
  '/account/': typeof AccountIndexRoute
  '/authors/': typeof AuthorsIndexRoute
  '/books/': typeof BooksIndexRoute
  '/categories/': typeof CategoriesIndexRoute
  '/ebooks/': typeof EbooksIndexRoute
  '/journals/': typeof JournalsIndexRoute
  '/thoughts/': typeof ThoughtsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/mission': typeof MissionRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/store-locator': typeof StoreLocatorRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/wishlist': typeof WishlistRoute
  '/account/orders': typeof AccountOrdersRoute
  '/authors/$slug': typeof AuthorsSlugRoute
  '/books/$slug': typeof BooksSlugRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/ebooks/$slug': typeof EbooksSlugRoute
  '/journals/$slug': typeof JournalsSlugRoute
  '/thoughts/$slug': typeof ThoughtsSlugRoute
  '/account': typeof AccountIndexRoute
  '/authors': typeof AuthorsIndexRoute
  '/books': typeof BooksIndexRoute
  '/categories': typeof CategoriesIndexRoute
  '/ebooks': typeof EbooksIndexRoute
  '/journals': typeof JournalsIndexRoute
  '/thoughts': typeof ThoughtsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/mission': typeof MissionRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/store-locator': typeof StoreLocatorRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/wishlist': typeof WishlistRoute
  '/account/orders': typeof AccountOrdersRoute
  '/authors/$slug': typeof AuthorsSlugRoute
  '/books/$slug': typeof BooksSlugRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/ebooks/$slug': typeof EbooksSlugRoute
  '/journals/$slug': typeof JournalsSlugRoute
  '/thoughts/$slug': typeof ThoughtsSlugRoute
  '/account/': typeof AccountIndexRoute
  '/authors/': typeof AuthorsIndexRoute
  '/books/': typeof BooksIndexRoute
  '/categories/': typeof CategoriesIndexRoute
  '/ebooks/': typeof EbooksIndexRoute
  '/journals/': typeof JournalsIndexRoute
  '/thoughts/': typeof ThoughtsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/gallery'
    | '/mission'
    | '/search'
    | '/sitemap.xml'
    | '/store-locator'
    | '/subscriptions'
    | '/wishlist'
    | '/account/orders'
    | '/authors/$slug'
    | '/books/$slug'
    | '/categories/$slug'
    | '/ebooks/$slug'
    | '/journals/$slug'
    | '/thoughts/$slug'
    | '/account/'
    | '/authors/'
    | '/books/'
    | '/categories/'
    | '/ebooks/'
    | '/journals/'
    | '/thoughts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/gallery'
    | '/mission'
    | '/search'
    | '/sitemap.xml'
    | '/store-locator'
    | '/subscriptions'
    | '/wishlist'
    | '/account/orders'
    | '/authors/$slug'
    | '/books/$slug'
    | '/categories/$slug'
    | '/ebooks/$slug'
    | '/journals/$slug'
    | '/thoughts/$slug'
    | '/account'
    | '/authors'
    | '/books'
    | '/categories'
    | '/ebooks'
    | '/journals'
    | '/thoughts'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/gallery'
    | '/mission'
    | '/search'
    | '/sitemap.xml'
    | '/store-locator'
    | '/subscriptions'
    | '/wishlist'
    | '/account/orders'
    | '/authors/$slug'
    | '/books/$slug'
    | '/categories/$slug'
    | '/ebooks/$slug'
    | '/journals/$slug'
    | '/thoughts/$slug'
    | '/account/'
    | '/authors/'
    | '/books/'
    | '/categories/'
    | '/ebooks/'
    | '/journals/'
    | '/thoughts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  GalleryRoute: typeof GalleryRoute
  MissionRoute: typeof MissionRoute
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StoreLocatorRoute: typeof StoreLocatorRoute
  SubscriptionsRoute: typeof SubscriptionsRoute
  WishlistRoute: typeof WishlistRoute
  AccountOrdersRoute: typeof AccountOrdersRoute
  AuthorsSlugRoute: typeof AuthorsSlugRoute
  BooksSlugRoute: typeof BooksSlugRoute
  CategoriesSlugRoute: typeof CategoriesSlugRoute
  EbooksSlugRoute: typeof EbooksSlugRoute
  JournalsSlugRoute: typeof JournalsSlugRoute
  ThoughtsSlugRoute: typeof ThoughtsSlugRoute
  AccountIndexRoute: typeof AccountIndexRoute
  AuthorsIndexRoute: typeof AuthorsIndexRoute
  BooksIndexRoute: typeof BooksIndexRoute
  CategoriesIndexRoute: typeof CategoriesIndexRoute
  EbooksIndexRoute: typeof EbooksIndexRoute
  JournalsIndexRoute: typeof JournalsIndexRoute
  ThoughtsIndexRoute: typeof ThoughtsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscriptions': {
      id: '/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof SubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store-locator': {
      id: '/store-locator'
      path: '/store-locator'
      fullPath: '/store-locator'
      preLoaderRoute: typeof StoreLocatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mission': {
      id: '/mission'
      path: '/mission'
      fullPath: '/mission'
      preLoaderRoute: typeof MissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thoughts/': {
      id: '/thoughts/'
      path: '/thoughts'
      fullPath: '/thoughts/'
      preLoaderRoute: typeof ThoughtsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journals/': {
      id: '/journals/'
      path: '/journals'
      fullPath: '/journals/'
      preLoaderRoute: typeof JournalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ebooks/': {
      id: '/ebooks/'
      path: '/ebooks'
      fullPath: '/ebooks/'
      preLoaderRoute: typeof EbooksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/': {
      id: '/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof CategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/': {
      id: '/books/'
      path: '/books'
      fullPath: '/books/'
      preLoaderRoute: typeof BooksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authors/': {
      id: '/authors/'
      path: '/authors'
      fullPath: '/authors/'
      preLoaderRoute: typeof AuthorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thoughts/$slug': {
      id: '/thoughts/$slug'
      path: '/thoughts/$slug'
      fullPath: '/thoughts/$slug'
      preLoaderRoute: typeof ThoughtsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journals/$slug': {
      id: '/journals/$slug'
      path: '/journals/$slug'
      fullPath: '/journals/$slug'
      preLoaderRoute: typeof JournalsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ebooks/$slug': {
      id: '/ebooks/$slug'
      path: '/ebooks/$slug'
      fullPath: '/ebooks/$slug'
      preLoaderRoute: typeof EbooksSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$slug': {
      id: '/categories/$slug'
      path: '/categories/$slug'
      fullPath: '/categories/$slug'
      preLoaderRoute: typeof CategoriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/$slug': {
      id: '/books/$slug'
      path: '/books/$slug'
      fullPath: '/books/$slug'
      preLoaderRoute: typeof BooksSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authors/$slug': {
      id: '/authors/$slug'
      path: '/authors/$slug'
      fullPath: '/authors/$slug'
      preLoaderRoute: typeof AuthorsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/orders': {
      id: '/account/orders'
      path: '/account/orders'
      fullPath: '/account/orders'
      preLoaderRoute: typeof AccountOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  GalleryRoute: GalleryRoute,
  MissionRoute: MissionRoute,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StoreLocatorRoute: StoreLocatorRoute,
  SubscriptionsRoute: SubscriptionsRoute,
  WishlistRoute: WishlistRoute,
  AccountOrdersRoute: AccountOrdersRoute,
  AuthorsSlugRoute: AuthorsSlugRoute,
  BooksSlugRoute: BooksSlugRoute,
  CategoriesSlugRoute: CategoriesSlugRoute,
  EbooksSlugRoute: EbooksSlugRoute,
  JournalsSlugRoute: JournalsSlugRoute,
  ThoughtsSlugRoute: ThoughtsSlugRoute,
  AccountIndexRoute: AccountIndexRoute,
  AuthorsIndexRoute: AuthorsIndexRoute,
  BooksIndexRoute: BooksIndexRoute,
  CategoriesIndexRoute: CategoriesIndexRoute,
  EbooksIndexRoute: EbooksIndexRoute,
  JournalsIndexRoute: JournalsIndexRoute,
  ThoughtsIndexRoute: ThoughtsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
